all: False
template: testify
packages:
  github.com/0xanonydxck/simple-bookstore/internal/book:
    config:
      dir: '{{.InterfaceDir}}'
      filename: 'mocks.go'
      pkgname: 'book'
      structname: 'Mock{{.InterfaceName}}'
    interfaces:
      Repository:
        configs:
          - filename: 'mock_repository.go'
            structname: 'MockRepository'
  github.com/0xanonydxck/simple-bookstore/internal/user:
    config:
      dir: '{{.InterfaceDir}}'
      filename: 'mocks.go'
      pkgname: 'user'
      structname: 'Mock{{.InterfaceName}}'
    interfaces:
      Repository:
        configs:
          - filename: 'mock_repository.go'
            structname: 'MockRepository'
  github.com/0xanonydxck/simple-bookstore/infrastructure/auth:
    config:
      dir: '{{.InterfaceDir}}'
      filename: 'mocks.go'
      pkgname: 'auth'
      structname: 'Mock{{.InterfaceName}}'
    interfaces:
      AuthEnforcer:
        configs:
          - filename: 'mock_enforcer.go'
            structname: 'MockAuthEnforcer'

